use crate::Span;

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Number(f64),
    BigInt(String),
    String(String),
    Identifier(String),
    Let,
    Var,
    Const,
    Function,
    Return,
    If,
    Else,
    While,
    For,
    Throw,
    Try,
    Catch,
    Finally,
    Switch,
    Case,
    Default,
    Break,
    New,
    This,
    Typeof,
    Instanceof,
    Continue,
    Delete,
    Void,
    In,
    Async,
    Await,
    True,
    False,
    Null,
    Undefined,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Assign,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    PlusPlus,
    MinusMinus,
    Equal,
    NotEqual,
    StrictEqual,
    StrictNotEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    And,
    Or,
    Bang,
    Question,
    Colon,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Comma,
    Semicolon,
    Dot,
    DotDotDot,
    Ampersand,
    Pipe,
    Caret,
    Tilde,
    LeftShift,
    RightShift,
    UnsignedRightShift,
    Arrow,
    Backtick,
    TemplateStart,
    TemplateText(String),
    TemplateExprStart,
    TemplateExprEnd,
    TemplateEnd,
    RegExp(String, String),
    Eof,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span) -> Self {
        Self { kind, span }
    }
}

pub fn keyword_or_identifier(text: String) -> TokenKind {
    match text.as_str() {
        "let" => TokenKind::Let,
        "var" => TokenKind::Var,
        "const" => TokenKind::Const,
        "function" => TokenKind::Function,
        "return" => TokenKind::Return,
        "if" => TokenKind::If,
        "else" => TokenKind::Else,
        "while" => TokenKind::While,
        "for" => TokenKind::For,
        "throw" => TokenKind::Throw,
        "try" => TokenKind::Try,
        "catch" => TokenKind::Catch,
        "finally" => TokenKind::Finally,
        "switch" => TokenKind::Switch,
        "case" => TokenKind::Case,
        "default" => TokenKind::Default,
        "break" => TokenKind::Break,
        "new" => TokenKind::New,
        "this" => TokenKind::This,
        "typeof" => TokenKind::Typeof,
        "instanceof" => TokenKind::Instanceof,
        "continue" => TokenKind::Continue,
        "delete" => TokenKind::Delete,
        "void" => TokenKind::Void,
        "in" => TokenKind::In,
        "async" => TokenKind::Async,
        "await" => TokenKind::Await,
        "true" => TokenKind::True,
        "false" => TokenKind::False,
        "null" => TokenKind::Null,
        "undefined" => TokenKind::Undefined,
        _ => TokenKind::Identifier(text),
    }
}
